### ISSUE TITLE
첨부된 관련 글꼴파일을 재배포시 라이센스가 명시되어야 합니다.

### ISSUE THREAD

**Issue by Jx2H** [leedongho0606/swavecountdown#2]
[여기](https://help.naver.com/support/contents/contents.help?serviceNo=1074&categoryNo=3497)에서 자세한 내용을 확인할 수 있습니다.

프로그램내 라이센스를 삽입하여 저작권에 위배되지 않게 처리해주세요.

**Comment by leedongho0606** [comment]
프로젝트 영구중단
